### ISSUE TITLE
Create a script for downloading camera link API headers

### ISSUE THREAD

**Issue by jackiryan** [nasa-jpl/LiveViewOpenSource#11]
Due to copyright reasons, we are not able to include the EDT PDV headers in our public repo. As a workaround, let's make a script that users can run during the installation process that will grab the EDT API headers from the web and install them in the proper source directory.

**Comment by maseca** [comment]
Need a little more clarification on destination source directory.  Also the headers can be installed via the executables [here](https://edt.com/file-category/pdv/)?  Do we want to use the generic linux version for RHEL or the rpm version?

**Comment by jackiryan** [comment]
Yeah, so your script will have to grab the .run file from that site that you linked. It's essentially a shell script. Next, assert that you are running on a linux operating system. Then execute the run file (probably needs to check/ask for sudo permissions). Assuming the installation completes successfully and everything was installed to /opt/EDTpdv/, copy *.h from that directory into a directory called "EDT_include/"

The alternative mode of operation is to ask for the EDT install directory at the beginning of the script. If the user hits enter then go and download per the above paragraph. If they give a location, attempt to copy headers from the given directory into the EDT_include directory.

**Comment by jackiryan** [comment]
This has been tested on the ucisair2 system. Also Max created a desktop icon there.
