### ISSUE TITLE
Setting backend FPS

### ISSUE THREAD

**Issue by JM-Anderson** [nasa-jpl/LiveViewOpenSource#35]
Setting the backend FPS is impossible to do while an image is being processed - this should be fixed.

While setting the backend FPS it is currently not possible to confirm whether your change has been accepted without trying to open an image. There should be a feature to confirm what the target back end FPS is.

**Comment by jackiryan** [comment]
Yeah, so my initial thinking was that having the FPS counter as a textbox that could be edited would be clever, but now I realize it's super janky. Here's an alternative:

Let's have a small square button next to the FPS counter that opens a little dialog that displays the current target FPS and has a spin box that lets you set the target FPS. Clicking "OK" to close the window adjusts the target FPS.
