### ISSUE TITLE
Unable to Create Folder

### ISSUE THREAD

**Issue by rvalenc** [nasa-jpl/LiveViewOpenSource#44]
Host: carbo

LiveView Release:
commit 32b339d1efdf55bb9d0ebd02438390ea7f08a100 (HEAD -> master)
Merge: b2e8097 03712cd
Author: Jacqueline Ryan 38086904+jackiryan@users.noreply.github.com
Date: Thu Jul 25 16:44:35 2019 -0700

Issue: LiveView does not create a folder using the following sequence:

        File => Save As => Create Folder =>  
/mnt/DATA1/prismII/test_data_EMIT_DCSE_EM/liveview_log/20190930_DCSEEM_LAB303_AMBIENT_FUNCTIONAL_FPAEMULATOR_ALLPERIPHERALS_OFF_GUIMODE_LIVEVIEW

**Comment by jackiryan** [comment]
Hi Robert, I am unable to reproduce this bug, perhaps this is more of a documentation problem? Once you pick a file name (even in a new directory) to save as, it will not write to that file until the "save frames" button is pushed, or ideally, the action is commanded over the network.
