### ISSUE TITLE
LiveView Core Dumps Unexpectedly

### ISSUE THREAD

**Issue by rvalenc** [nasa-jpl/LiveViewOpenSource#45]
Host: carbo

LiveView Release:
commit 32b339d1efdf55bb9d0ebd02438390ea7f08a100 (HEAD -> master)
Merge: b2e8097 03712cd
Author: Jacqueline Ryan 38086904+jackiryan@users.noreply.github.com
Date: Thu Jul 25 16:44:35 2019 -0700

Issue:  During PBAT test 7.7.2.1, LiveView GUI  suddenly closed and core dumped. 
           This fault is not easy to reproduce, but it happened 2 weeks ago.

i will provide more details later. 

It was related to storing images during a p2serial_gui -> Acquire -> Start Acquire command.

**Comment by rvalenc** [comment]
i have not been able to reproduce the error. 
i was runnning on carbo. 

i found the snap i took after GUI disappeared..

![Screenshot at 2019-09-30 13-50-58](https://user-images.githubusercontent.com/33501006/66087814-a7062e80-e52d-11e9-9822-487da6a59227.png)

**Comment by jackiryan** [comment]
Going to close this for now, as the issue has not been reproduced and there is not conclusive evidence that it still exists.
